@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.trollmonkey.butchercraft_tannery;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;